# Generated by bootstrap-backend.sh. Safe to commit: it names a bucket, not a
# credential, and the bucket is private.
bucket       = "sandbox-factory-tfstate-510863815875"
key          = "sandbox-factory/terraform.tfstate"
region       = "us-east-1"
encrypt = true

# State locking is deliberately absent. `use_lockfile` (S3 native locking) needs
# Terraform 1.10+, and this machine runs 1.5.7; the older alternative is a
# DynamoDB table, which is a resource to create and pay for so that a single
# operator cannot race themselves. Revisit if a second person or CI ever runs
# `apply` — CI only runs `plan`, which takes no lock.
