# Generated by bootstrap-backend.sh. Safe to commit: it names a bucket, not a
# credential, and the bucket is private.
bucket       = "sandbox-factory-tfstate-510863815875"
key          = "sandbox-factory/terraform.tfstate"
region       = "us-east-1"
encrypt      = true
use_lockfile = true

# Locking: `apply` is run from more than one machine, so a run holds a lock
# object (`<key>.tflock`) beside the state, and a second run fails instead of
# racing it. S3 native locking needs Terraform 1.11+ (versions.tf enforces it)
# and no DynamoDB table. CI's plan never takes the lock: it reads the state
# with `state pull` and plans against a local copy.
