#!/usr/bin/env bash
#
# Create the S3 bucket that holds Terraform state.
#
#   ./infra/scripts/bootstrap-backend.sh
#
# Run once, by hand, then `terraform init -backend-config=backend.hcl`: the
# bucket cannot be managed by the state it holds. Versioning is on because
# losing state is unrecoverable. Locking uses S3 native lock files, so there is
# no DynamoDB table to create; the generated backend.hcl says why.

set -euo pipefail

PROJECT="${PROJECT:-sandbox-factory}"
REGION="${AWS_REGION:-us-east-1}"
ACCOUNT="$(aws sts get-caller-identity --query Account --output text)"
BUCKET="${PROJECT}-tfstate-${ACCOUNT}"

echo "Bootstrapping Terraform state backend"
echo "  bucket:  $BUCKET"
echo "  region:  $REGION"
echo

if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
  echo "Bucket already exists — nothing to do."
else
  # us-east-1 alone rejects a location constraint; every other region needs it.
  if [[ "$REGION" == "us-east-1" ]]; then
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION"
  else
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" \
      --create-bucket-configuration "LocationConstraint=$REGION"
  fi
  echo "Created $BUCKET"
fi

aws s3api put-bucket-versioning \
  --bucket "$BUCKET" \
  --versioning-configuration Status=Enabled
echo "Versioning enabled"

aws s3api put-bucket-encryption \
  --bucket "$BUCKET" \
  --server-side-encryption-configuration \
  '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
echo "Encryption enabled"

# State holds resource ids and a generated secret. It must never be public.
aws s3api put-public-access-block \
  --bucket "$BUCKET" \
  --public-access-block-configuration \
  "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
echo "Public access blocked"

cat > "$(dirname "$0")/../backend.hcl" <<EOF
# Generated by bootstrap-backend.sh. Safe to commit: it names a bucket, not a
# credential, and the bucket is private.
bucket       = "$BUCKET"
key          = "$PROJECT/terraform.tfstate"
region       = "$REGION"
encrypt      = true
use_lockfile = true

# Locking: \`apply\` is run from more than one machine, so a run holds a lock
# object (\`<key>.tflock\`) beside the state, and a second run fails instead of
# racing it. S3 native locking needs Terraform 1.11+ (versions.tf enforces it)
# and no DynamoDB table. CI's plan never takes the lock: it reads the state
# with \`state pull\` and plans against a local copy.
EOF

echo
echo "Wrote infra/backend.hcl"
echo
echo "Next:"
echo "  cd infra && terraform init -backend-config=backend.hcl"
