#!/usr/bin/env bash
#
# Create the S3 bucket that holds Terraform state.
#
#   ./infra/scripts/bootstrap-backend.sh
#
# The chicken-and-egg step: Terraform needs somewhere to keep state before it
# can manage anything, and that somewhere cannot itself be managed by the state
# it holds. Run once, by hand, then `terraform init -backend-config=backend.hcl`.
#
# Versioning is on because state is the one file whose loss is unrecoverable —
# it is the only record of which real resources Terraform believes it owns.
#
# No state locking. S3 native locking (`use_lockfile`) needs Terraform 1.10+,
# and the older alternative is a DynamoDB table — a resource to create and pay
# for so that a single operator cannot race themselves. The generated
# backend.hcl says the same, and where to revisit it.

set -euo pipefail

PROJECT="${PROJECT:-sandbox-factory}"
REGION="${AWS_REGION:-us-east-1}"
ACCOUNT="$(aws sts get-caller-identity --query Account --output text)"
BUCKET="${PROJECT}-tfstate-${ACCOUNT}"

echo "Bootstrapping Terraform state backend"
echo "  bucket:  $BUCKET"
echo "  region:  $REGION"
echo

if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
  echo "Bucket already exists — nothing to do."
else
  # us-east-1 is the one region where CreateBucket must NOT be given a location
  # constraint. Every other region requires it.
  if [[ "$REGION" == "us-east-1" ]]; then
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION"
  else
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" \
      --create-bucket-configuration "LocationConstraint=$REGION"
  fi
  echo "Created $BUCKET"
fi

aws s3api put-bucket-versioning \
  --bucket "$BUCKET" \
  --versioning-configuration Status=Enabled
echo "Versioning enabled"

aws s3api put-bucket-encryption \
  --bucket "$BUCKET" \
  --server-side-encryption-configuration \
  '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
echo "Encryption enabled"

# State contains resource identifiers and the generated database password. It
# must never be public.
aws s3api put-public-access-block \
  --bucket "$BUCKET" \
  --public-access-block-configuration \
  "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
echo "Public access blocked"

cat > "$(dirname "$0")/../backend.hcl" <<EOF
# Generated by bootstrap-backend.sh. Safe to commit: it names a bucket, not a
# credential, and the bucket is private.
bucket       = "$BUCKET"
key          = "$PROJECT/terraform.tfstate"
region       = "$REGION"
encrypt = true

# State locking is deliberately absent. \`use_lockfile\` (S3 native locking) needs
# Terraform 1.10+; the older alternative is a DynamoDB table, which is a
# resource to create and pay for so that a single operator cannot race
# themselves. Revisit if a second person or CI ever runs \`apply\` — CI only runs
# \`plan\`, which takes no lock.
EOF

echo
echo "Wrote infra/backend.hcl"
echo
echo "Next:"
echo "  cd infra && terraform init -backend-config=backend.hcl"
