#!/usr/bin/env bash
#
# Create the S3 bucket that holds Terraform state.
#
#   ./infra/scripts/bootstrap-backend.sh
#
# Run once, by hand, then `terraform init -backend-config=backend.hcl`: the
# bucket cannot be managed by the state it holds. Versioning is on because
# losing state is unrecoverable. No state locking, deliberately; the generated
# backend.hcl says why and when to revisit it.

set -euo pipefail

PROJECT="${PROJECT:-sandbox-factory}"
REGION="${AWS_REGION:-us-east-1}"
ACCOUNT="$(aws sts get-caller-identity --query Account --output text)"
BUCKET="${PROJECT}-tfstate-${ACCOUNT}"

echo "Bootstrapping Terraform state backend"
echo "  bucket:  $BUCKET"
echo "  region:  $REGION"
echo

if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
  echo "Bucket already exists — nothing to do."
else
  # us-east-1 alone rejects a location constraint; every other region needs it.
  if [[ "$REGION" == "us-east-1" ]]; then
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION"
  else
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" \
      --create-bucket-configuration "LocationConstraint=$REGION"
  fi
  echo "Created $BUCKET"
fi

aws s3api put-bucket-versioning \
  --bucket "$BUCKET" \
  --versioning-configuration Status=Enabled
echo "Versioning enabled"

aws s3api put-bucket-encryption \
  --bucket "$BUCKET" \
  --server-side-encryption-configuration \
  '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
echo "Encryption enabled"

# State holds resource ids and a generated secret. It must never be public.
aws s3api put-public-access-block \
  --bucket "$BUCKET" \
  --public-access-block-configuration \
  "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
echo "Public access blocked"

cat > "$(dirname "$0")/../backend.hcl" <<EOF
# Generated by bootstrap-backend.sh. Safe to commit: it names a bucket, not a
# credential, and the bucket is private.
bucket       = "$BUCKET"
key          = "$PROJECT/terraform.tfstate"
region       = "$REGION"
encrypt = true

# State locking is deliberately absent. \`use_lockfile\` (S3 native locking) needs
# Terraform 1.10+; the older alternative is a DynamoDB table, which is a
# resource to create and pay for so that a single operator cannot race
# themselves. Revisit if a second person or CI ever runs \`apply\` — CI only runs
# \`plan\`, which takes no lock.
EOF

echo
echo "Wrote infra/backend.hcl"
echo
echo "Next:"
echo "  cd infra && terraform init -backend-config=backend.hcl"
