-- A sandbox version can be generated rather than sliced: an agent writes a
-- starter from the bounty's text when the sandbox has no repository. Such a
-- run reads no snapshot, so a run is owned by its organization directly
-- rather than through its snapshot's repository, and a version names either
-- its slice inputs or its starter run.
--
-- Generated by drizzle-kit, then edited by hand in one place: the owner
-- column is added nullable, backfilled from each run's snapshot, and only
-- then made NOT NULL, because drizzle-kit adds it NOT NULL outright, which
-- fails on any existing run. Every existing run has a snapshot, and every
-- snapshot a repository, so the backfill leaves no row without an owner.
ALTER TABLE "analysis_run" ALTER COLUMN "snapshot_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sandbox_version_source" ALTER COLUMN "source_snapshot_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sandbox_version_source" ALTER COLUMN "slice_run_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sandbox_version_source" ALTER COLUMN "manifest_sha256" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "sandbox_version_source" ALTER COLUMN "contract_sha256" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "analysis_run" ADD COLUMN "organization_id" text;--> statement-breakpoint
UPDATE "analysis_run" a
SET "organization_id" = r."organization_id"
FROM "repo_snapshot" s
JOIN "github_repo" r ON r."id" = s."repo_id"
WHERE s."id" = a."snapshot_id";--> statement-breakpoint
ALTER TABLE "analysis_run" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sandbox_version_source" ADD COLUMN "starter_run_id" text;--> statement-breakpoint
ALTER TABLE "sandbox_version_source" ADD COLUMN "starter_sha256" text;--> statement-breakpoint
ALTER TABLE "analysis_run" ADD CONSTRAINT "analysis_run_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sandbox_version_source" ADD CONSTRAINT "sandbox_version_source_starter_run_id_analysis_run_id_fk" FOREIGN KEY ("starter_run_id") REFERENCES "public"."analysis_run"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "analysis_run_organization_id_idx" ON "analysis_run" USING btree ("organization_id");--> statement-breakpoint
ALTER TABLE "sandbox_version_source" ADD CONSTRAINT "sandbox_version_source_origin_check" CHECK (("sandbox_version_source"."slice_run_id" is not null and "sandbox_version_source"."source_snapshot_id" is not null and "sandbox_version_source"."manifest_sha256" is not null and "sandbox_version_source"."contract_sha256" is not null and "sandbox_version_source"."starter_run_id" is null) or ("sandbox_version_source"."slice_run_id" is null and "sandbox_version_source"."source_snapshot_id" is null and "sandbox_version_source"."manifest_sha256" is null and "sandbox_version_source"."contract_sha256" is null and "sandbox_version_source"."starter_run_id" is not null));
