-- A proposal's version: how many times what it says has been approved,
-- moved only by an approval of something changed since the last one, and
-- when the current one was approved.
--
-- Generated by drizzle-kit, then edited by hand in one place: the approved
-- proposals are backfilled as their first version, approved when they were
-- decided, before the checks that an approved proposal is a version. What a
-- proposal now proposed was once approved as is not recorded, so it starts
-- with none and its next approval is its version 1.
ALTER TABLE "bounty_proposal" ADD COLUMN "version" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "bounty_proposal" ADD COLUMN "versioned_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "bounty_proposal" ADD COLUMN "version_revision" integer;--> statement-breakpoint
UPDATE "bounty_proposal"
SET "version" = 1,
  "versioned_at" = coalesce("decided_at", "updated_at"),
  "version_revision" = "revision"
WHERE "status" = 'approved';--> statement-breakpoint
ALTER TABLE "bounty_proposal" ADD CONSTRAINT "bounty_proposal_version_check" CHECK (("bounty_proposal"."version" = 0 AND "bounty_proposal"."versioned_at" IS NULL AND "bounty_proposal"."version_revision" IS NULL) OR ("bounty_proposal"."version" > 0 AND "bounty_proposal"."versioned_at" IS NOT NULL AND "bounty_proposal"."version_revision" > 0));--> statement-breakpoint
ALTER TABLE "bounty_proposal" ADD CONSTRAINT "bounty_proposal_approved_version_check" CHECK ("bounty_proposal"."status" <> 'approved' OR "bounty_proposal"."version" > 0);