-- A bounty's overview is versioned, and a sandbox version records the
-- bounty version it was built on.
--
-- Generated by drizzle-kit, then edited by hand at the end: every bounty's
-- text as it stands is its overview's version 1, and a sandbox version whose
-- task was taken from its proposal's current approval records that version.
-- One taken from an approval since moved past cannot be told apart from one
-- before an unchanged re-approval, so it is left null and reads as built on
-- an earlier version.
CREATE TABLE "bounty_version" (
	"bounty_id" text NOT NULL,
	"version" integer NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"created_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "bounty_version_bounty_id_version_pk" PRIMARY KEY("bounty_id","version"),
	CONSTRAINT "bounty_version_version_check" CHECK ("bounty_version"."version" > 0)
);
--> statement-breakpoint
ALTER TABLE "bounty" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "sandbox_version_source" ADD COLUMN "proposal_version" integer;--> statement-breakpoint
ALTER TABLE "bounty_version" ADD CONSTRAINT "bounty_version_bounty_id_bounty_id_fk" FOREIGN KEY ("bounty_id") REFERENCES "public"."bounty"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bounty_version" ADD CONSTRAINT "bounty_version_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bounty" ADD CONSTRAINT "bounty_version_check" CHECK ("bounty"."version" > 0);--> statement-breakpoint
INSERT INTO "bounty_version" ("bounty_id", "version", "title", "description", "created_by", "created_at")
SELECT "id", 1, "title", "description", "created_by", "updated_at" FROM "bounty";--> statement-breakpoint
UPDATE "sandbox_version_source" s
SET "proposal_version" = p."version"
FROM "bounty_proposal" p
WHERE p."id" = s."approved_task"->'pricing'->>'proposalId'
  AND s."approved_task"->'pricing'->>'status' = 'approved'
  AND p."version" > 0
  AND p."version_revision" = (s."approved_task"->'pricing'->>'proposalRevision')::integer;