-- A repository's context is one commit for every context builder: the
-- snapshot "Build all" last ran on, rather than whichever one the page has
-- chosen.
--
-- Generated by drizzle-kit, then edited by hand in one place: the backfill
-- points each repository at the snapshot of its newest builder run, so a
-- context built before this keeps showing. A run that names its builder came
-- from the repository page; graphify's do not, and the profiler queues those
-- for bounties too, so they count only where no builder named itself.
ALTER TABLE "github_repo" ADD COLUMN "context_snapshot_id" text;--> statement-breakpoint
UPDATE "github_repo" r
SET "context_snapshot_id" = (
  SELECT s."id"
  FROM "analysis_run" a
  JOIN "repo_snapshot" s ON s."id" = a."snapshot_id"
  WHERE s."repo_id" = r."id"
    AND a."tool" IN ('graphify', 'dependency_cruiser', 'deepwiki', 'abstractions', 'data_model')
  ORDER BY (a."params" ? 'builder') DESC, a."created_at" DESC
  LIMIT 1
);
