-- A bounty names no repository: its work may touch any the workspace has
-- connected. The bounty's and the board's repository go; a proposal records
-- the repositories its drafting said the work touches, and a profile is
-- measured for each.
--
-- Generated by drizzle-kit, then edited by hand in one place: before the
-- proposal's snapshot column is dropped, the repository it was drafted
-- beside becomes the one repository it touches, so a proposal sized before
-- keeps what its profile and sandbox were measured from.
ALTER TABLE "bounty_profile" DROP CONSTRAINT "bounty_profile_proposal_revision_unique";--> statement-breakpoint
ALTER TABLE "bounty" DROP CONSTRAINT "bounty_repo_id_github_repo_id_fk";
--> statement-breakpoint
ALTER TABLE "bounty_proposal" DROP CONSTRAINT "bounty_proposal_repo_snapshot_id_repo_snapshot_id_fk";
--> statement-breakpoint
ALTER TABLE "jira_board" DROP CONSTRAINT "jira_board_source_repo_id_github_repo_id_fk";
--> statement-breakpoint
DROP INDEX "bounty_repo_id_idx";--> statement-breakpoint
DROP INDEX "bounty_proposal_repo_snapshot_id_idx";--> statement-breakpoint
DROP INDEX "jira_board_source_repo_id_idx";--> statement-breakpoint
ALTER TABLE "bounty_proposal" ADD COLUMN "repositories" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
CREATE INDEX "bounty_proposal_repositories_idx" ON "bounty_proposal" USING gin ("repositories");--> statement-breakpoint
UPDATE "bounty_proposal" p
SET "repositories" = jsonb_build_array(jsonb_build_object('repoId', s."repo_id", 'snapshotId', s."id"))
FROM "repo_snapshot" s
WHERE s."id" = p."repo_snapshot_id";--> statement-breakpoint
ALTER TABLE "bounty" DROP COLUMN "repo_id";--> statement-breakpoint
ALTER TABLE "bounty_proposal" DROP COLUMN "repo_snapshot_id";--> statement-breakpoint
ALTER TABLE "jira_board" DROP COLUMN "source_repo_id";--> statement-breakpoint
ALTER TABLE "bounty_profile" ADD CONSTRAINT "bounty_profile_proposal_revision_snapshot_unique" UNIQUE("proposal_id","spec_revision","snapshot_id");