/**
 * The sandbox build adapter: from a version's private provenance and the
 * slice it was cut from, a standalone project, its hidden tests and a
 * baseline check in a fresh evaluation job.
 *
 * Everything the output binds to arrives as run parameters and is checked
 * against the version record and the slice artifacts before a byte is
 * generated: a draft that changed after the run was queued fails rather
 * than building a candidate for the wrong transform. Source bytes are read
 * at the pinned commit and verified against the slice manifest's hashes.
 * Aliases are applied with the inverse proof, the project is generated by
 * the pure generator in `packages/core`, and the baseline runs the public
 * commands plus every hidden test in a job the provider creates and
 * destroys. Logs stay fixed lines; the job's output is not stored.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { nearestCompilerOptions } from "./compiler-config.js";
export { nearestCompilerOptions } from "./compiler-config.js";
import {
  EVALUATION_LIMITS,
  PRIVATE_TESTS_DIR,
  PSEUDONYMS_FILE,
  PSEUDONYMS_SCHEMA_VERSION,
  RUN_PATH,
  SANDBOX_BUILD_RUN_VERSION,
  SANDBOX_BUILD_SCHEMA_VERSION,
  SANDBOX_TOOLCHAIN,
  applyAliases,
  baselineVerdict,
  jsonLeaves,
  withJsonLeaves,
  buildSummary,
  canonicalJson,
  generateProject,
  isSandboxBuildParams,
  runtimePath,
  transformConfigOf,
} from "sandbox-factory";
import type {
  AcceptanceTest,
  AliasRule,
  BaselineReport,
  BaselineStep,
  BoundaryContract,
  BuildFileRecord,
  EvaluationEnvironment,
  EvaluationProvider,
  GeneratedFile,
  PrivateTestOutcome,
  ProjectBlocker,
  ProjectSource,
  ProjectStub,
  SandboxBuildManifest,
  SpecDraft,
  StageExecution,
} from "sandbox-factory";
import {
  boundaryContractSchema,
  sandboxFixtureSchema,
  specDraftSchema,
} from "@sandbox-factory/shared";
import { AnalysisError } from "../errors.js";
import { snapshotOf } from "./adapter.js";
import type { ArtifactFile, ToolAdapter, ToolRunInput } from "./adapter.js";
import { loadSliceRun, readIncludedSource } from "./slice-run.js";
import { sha256 } from "./slice/hash.js";
import { NODE_BUILTINS } from "./slice/typescript.js";

export interface SandboxBuildOptions {
  /**
   * Where the baseline runs. `null` when the worker has none configured:
   * builds then fail with `evaluation_failed` before generating anything.
   */
  readonly provider: EvaluationProvider | null;
  readonly now?: () => Date;
}

/**
 * The spec and the contract's symbols travel through aliasing as
 * pseudo-files, one per string leaf (`jsonLeaves`), so unscoped rules
 * rename their text consistently with the source and the stubs while their
 * keys and shape stay as they are. Module paths and importers are left
 * alone: path rules rename files, and the generator maps original paths to
 * aliased ones.
 */
const SPEC_PSEUDO_PATH = "__approved_spec__.json";
/**
 * Fixtures ride along the same way, so a renamed symbol keeps its fixture;
 * the walkthrough goes through at its own path, like copied source.
 */
const FIXTURES_PSEUDO_PATH = "__fixtures__.json";
const CONTRACT_PSEUDO_PATH = "__boundary_symbols__.json";
type ModuleSymbols = BoundaryContract["outbound"][number]["symbols"];
interface ContractSymbols {
  outbound: ModuleSymbols[];
  inbound: ModuleSymbols[];
}
function symbolsOf(contract: BoundaryContract): ContractSymbols {
  return {
    outbound: contract.outbound.map((module) => module.symbols),
    inbound: contract.inbound.map((module) => module.symbols),
  };
}
function withSymbols(
  contract: BoundaryContract,
  parsed: ContractSymbols,
): BoundaryContract {
  return {
    ...contract,
    outbound: contract.outbound.map((module, index) => ({
      ...module,
      symbols: parsed.outbound[index] ?? module.symbols,
    })),
    inbound: contract.inbound.map((module, index) => ({
      ...module,
      symbols: parsed.inbound[index] ?? module.symbols,
    })),
  };
}
const compare = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

const fixtureListSchema = sandboxFixtureSchema.array();
/**
 * Whether a value that read as its schema before renaming still does: a
 * value that never did (none, or stored before the schema tightened) is
 * not the alias table's to break.
 */
function stillReads(
  schema: { safeParse(value: unknown): { success: boolean } },
  before: unknown,
  after: unknown,
): boolean {
  return (
    before === null ||
    !schema.safeParse(before).success ||
    schema.safeParse(after).success
  );
}

/**
 * What a hidden test did, from its exit and the runner's TAP report.
 *
 * The runner exits 1 both when a test failed and when the file never ran
 * its tests at all: it threw while loading, or imported something that is
 * not there. Only the first is the failure a hidden test is expected to
 * show on the baseline; the second is a broken test, and a build or harness
 * failure is never accepted as the expected one. The runner reports a file
 * that failed as a whole as one point with `ERR_TEST_FAILURE` and the
 * file's exit code, both at the point's own indent; a test that failed is a
 * point with its own error, whose `code` may be the same but whose values,
 * an asserted `{ exitCode }` among them, are indented deeper. A report that
 * says neither, cut short or missing, is an error.
 */
export function privateTestOutcome(
  step: Pick<BaselineStep, "exitCode" | "timedOut">,
  stdout: string,
): PrivateTestOutcome["observed"] {
  if (step.timedOut || step.exitCode === null) return "error";
  if (step.exitCode === 0) return "pass";
  if (step.exitCode !== 1) return "error";
  const wholeFile =
    /^ {2}code: 'ERR_TEST_FAILURE'$/m.test(stdout) &&
    /^ {2}exitCode: \d+$/m.test(stdout);
  if (wholeFile) return "error";
  const failed = /^# fail (\d+)$/m.exec(stdout);
  return failed !== null && Number(failed[1]) > 0 ? "fail" : "error";
}

/** Where a build writes the table its public files were renamed by. */
export const PSEUDONYMS_PATH = `private/${PSEUDONYMS_FILE}`;

export function buildArtifactKind(path: string): ArtifactFile["kind"] {
  if (path === "build-manifest.json") return "build_manifest";
  if (path === "baseline.json") return "baseline_report";
  if (path === PSEUDONYMS_PATH) return "pseudonyms";
  if (path.startsWith("project/")) return "project_file";
  if (path.startsWith("private/")) return "private_test";
  return "other";
}

/** What one baseline step printed, for a caller that shows it to an agent. */
export type StepObserver = (
  step: BaselineStep,
  output: { readonly stdout: string; readonly stderr: string },
) => void;

async function runBaseline(
  provider: EvaluationProvider,
  input: {
    readonly label: string;
    readonly files: readonly GeneratedFile[];
    readonly acceptanceTests: readonly AcceptanceTest[];
    readonly signal: AbortSignal;
    readonly log: (line: string) => void;
    readonly now: () => Date;
    readonly onStep?: StepObserver;
  },
): Promise<{
  baseline: BaselineReport;
  evaluator: EvaluationEnvironment;
  lockfile: string | null;
}> {
  let job;
  try {
    job = await provider.create({ label: input.label, signal: input.signal });
  } catch (error) {
    if (input.signal.aborted) throw error;
    throw new AnalysisError("evaluation_failed");
  }
  const staged = input.files.map((file) => ({
    path: file.path,
    text: file.text,
  }));
  const execution = {
    stage: "baseline" as const,
    sequence: 1,
    environment: job.environment,
    jobId: job.id,
    inputsSha256: sha256(
      canonicalJson(staged.map((file) => [file.path, sha256(file.text)])),
    ),
    state: "created" as StageExecution["state"],
    startedAt: input.now().toISOString(),
    finishedAt: null as string | null,
    teardown: "pending" as StageExecution["teardown"],
  };
  const steps: BaselineStep[] = [];
  const privateTests: PrivateTestOutcome[] = [];
  let lockfile: string | null = null;
  try {
    await job.stage(staged);
    execution.state = "running";
    const run = async (
      name: BaselineStep["name"],
      argv: readonly string[],
      path: string | null = null,
    ) => {
      input.signal.throwIfAborted();
      const result = await job.exec({
        argv,
        env: {},
        limits: EVALUATION_LIMITS,
      });
      const step: BaselineStep = {
        name,
        argv,
        exitCode: result.exitCode,
        timedOut: result.timedOut,
        ok: !result.timedOut && result.exitCode === 0,
        path,
      };
      steps.push(step);
      input.onStep?.(step, { stdout: result.stdout, stderr: result.stderr });
      return { step, stdout: result.stdout };
    };
    // Trusted preparation pins the dependency tree; the clean install,
    // build and tests then run against exactly that lockfile.
    const { step: prepared } = await run("prepare", [
      "npm",
      "install",
      "--package-lock-only",
      "--ignore-scripts",
      "--no-audit",
      "--no-fund",
    ]);
    if (prepared.ok) {
      lockfile = await job.read("package-lock.json");
      const { step: installed } = await run("install", [
        "npm",
        "ci",
        "--ignore-scripts",
        "--no-audit",
        "--no-fund",
      ]);
      if (installed.ok) {
        const { step: built } = await run("build", ["npm", "run", "build"]);
        if (built.ok) {
          // The walkthrough a developer runs first must run on the baseline.
          await run("dev", ["npm", "run", "dev"]);
          await run("public-tests", ["npm", "test"]);
          for (const test of input.acceptanceTests) {
            const { step, stdout } = await run(
              "private-test",
              [
                "node",
                "--env-file=sandbox.env",
                "--test",
                "--test-reporter=tap",
                runtimePath(test.path),
              ],
              test.path,
            );
            const observed = privateTestOutcome(step, stdout);
            const ok = observed === test.expectedBaseline;
            privateTests.push({
              path: test.path,
              expected: test.expectedBaseline,
              observed,
              ok,
            });
            steps[steps.length - 1] = { ...step, ok };
          }
        }
      }
    }
    execution.state = "succeeded";
  } catch (error) {
    execution.state = input.signal.aborted ? "cancelled" : "failed";
    if (input.signal.aborted) throw error;
    throw new AnalysisError("evaluation_failed");
  } finally {
    execution.finishedAt = input.now().toISOString();
    try {
      await job.destroy();
      execution.teardown = "destroyed";
    } catch {
      execution.teardown = "failed";
    }
    input.log(
      `Evaluation job ${job.id} ${execution.state}, teardown ${execution.teardown}.`,
    );
  }
  const verdict = baselineVerdict({ steps, privateTests });
  return {
    baseline: {
      executions: [execution],
      steps,
      privateTests,
      ok: verdict.ok,
      reasons: verdict.reasons,
    },
    evaluator: job.environment,
    lockfile,
  };
}

/**
 * What a build manifest binds its files to: the slice, or a generated
 * version's starter, and the transform and task they were built for.
 */
export type BuildBindings = Pick<
  SandboxBuildManifest,
  | "sourceSnapshotId"
  | "sourceCommitSha"
  | "sliceRunId"
  | "manifestSha256"
  | "contractSha256"
  | "starterSha256"
  | "transformConfigSha256"
  | "approvedTaskSha256"
>;

/**
 * Writes a build's outputs: `build-manifest.json` hashing and classifying
 * every generated file, `baseline.json` when the baseline ran, each file
 * under `project/` or, for a hidden test, `private/`, and the alias table
 * as `private/pseudonym.lunox`. The public sandbox is `project/`; the
 * private one is the same files read back through that table, so a build
 * makes both.
 */
export async function writeBuildOutputs(input: {
  readonly outDir: string;
  readonly toolVersion: string;
  readonly sandboxVersionId: string;
  readonly bindings: BuildBindings;
  /** The table the files were renamed by, written as `pseudonym.lunox`. */
  readonly aliasRules: readonly AliasRule[];
  readonly files: readonly GeneratedFile[];
  readonly importRewrites: SandboxBuildManifest["importRewrites"];
  readonly renames: SandboxBuildManifest["renames"];
  readonly dependencies: SandboxBuildManifest["dependencies"];
  readonly baseline: BaselineReport | null;
  readonly evaluator: EvaluationEnvironment | null;
  readonly blockers: readonly ProjectBlocker[];
}): Promise<{ manifest: SandboxBuildManifest; written: ArtifactFile[] }> {
  const { baseline, blockers } = input;
  const files = [...input.files].sort((a, b) => compare(a.path, b.path));
  const records: BuildFileRecord[] = files.map((file) => ({
    path: file.path,
    sha256: sha256(file.text),
    sizeBytes: Buffer.byteLength(file.text),
    class: file.class,
    public: file.public,
  }));
  const hashOf = (subset: readonly BuildFileRecord[]) =>
    sha256(canonicalJson(subset.map((record) => [record.path, record.sha256])));
  const manifest: SandboxBuildManifest = {
    schemaVersion: SANDBOX_BUILD_SCHEMA_VERSION,
    toolVersion: input.toolVersion,
    sandboxVersionId: input.sandboxVersionId,
    ...input.bindings,
    toolchain: SANDBOX_TOOLCHAIN,
    toolchainDigest: sha256(canonicalJson(SANDBOX_TOOLCHAIN)),
    evaluator: input.evaluator,
    files: records,
    importRewrites: input.importRewrites,
    renames: input.renames,
    dependencies: input.dependencies,
    harnessSha256: hashOf(
      records.filter((record) => record.class !== "source"),
    ),
    publicTestsSha256: hashOf(
      records.filter((record) => record.class === "test-public"),
    ),
    privateTestsSha256: hashOf(
      records.filter((record) => record.class === "test-private"),
    ),
    publicProjectSha256: hashOf(records.filter((record) => record.public)),
    baseline,
    blockers,
    ready: blockers.length === 0 && baseline?.ok === true,
  };
  await mkdir(input.outDir, { recursive: true });
  const outputs: {
    path: string;
    text: string;
    meta: Record<string, unknown> | null;
  }[] = [
    {
      path: "build-manifest.json",
      text: canonicalJson(manifest),
      meta: buildSummary(manifest) as unknown as Record<string, unknown>,
    },
    ...(baseline === null
      ? []
      : [{ path: "baseline.json", text: canonicalJson(baseline), meta: null }]),
    {
      path: PSEUDONYMS_PATH,
      text: canonicalJson({
        schemaVersion: PSEUDONYMS_SCHEMA_VERSION,
        rules: input.aliasRules,
      }),
      meta: { rules: input.aliasRules.length },
    },
    ...files.map((file) => ({
      path: file.public
        ? `project/${file.path}`
        : `private/${file.path.replace(`${PRIVATE_TESTS_DIR}/`, "")}`,
      text: file.text,
      meta: null,
    })),
  ];
  const written: ArtifactFile[] = [];
  for (const output of outputs) {
    const absolutePath = join(input.outDir, output.path);
    await mkdir(dirname(absolutePath), { recursive: true });
    await writeFile(absolutePath, output.text, "utf8");
    written.push({
      path: output.path,
      absolutePath,
      kind: buildArtifactKind(output.path),
      contentType:
        output.path.endsWith(".json") || output.path === PSEUDONYMS_PATH
          ? "application/json"
          : "text/plain; charset=utf-8",
      meta: output.meta,
    });
  }
  return { manifest, written: written.sort((a, b) => compare(a.path, b.path)) };
}

/**
 * Runs the baseline for generated files and folds its result in: the
 * lockfile it resolved joins the files, and a failed baseline is a
 * blocker. What a build and a starter both do once their files exist.
 */
export async function baselineOf(
  provider: EvaluationProvider,
  input: {
    readonly label: string;
    readonly files: GeneratedFile[];
    readonly acceptanceTests: readonly AcceptanceTest[];
    readonly blockers: ProjectBlocker[];
    readonly signal: AbortSignal;
    readonly log: (line: string) => void;
    readonly now: () => Date;
    /** Each step's output, for an agent fixing its own project; never logged. */
    readonly onStep?: StepObserver;
  },
): Promise<{ baseline: BaselineReport; evaluator: EvaluationEnvironment }> {
  const result = await runBaseline(provider, input);
  if (result.lockfile !== null)
    input.files.push({
      path: "package-lock.json",
      text: result.lockfile,
      class: "config",
      public: true,
    });
  if (!result.baseline.ok)
    input.blockers.push({
      code: "baseline_failed",
      file: null,
      detail: result.baseline.reasons.join(" "),
    });
  input.log(
    result.baseline.ok
      ? "Baseline check passed."
      : `Baseline check failed: ${result.baseline.reasons.length} reason(s).`,
  );
  return { baseline: result.baseline, evaluator: result.evaluator };
}

export function createSandboxBuildAdapter(
  options: SandboxBuildOptions,
): ToolAdapter {
  const now = options.now ?? (() => new Date());
  return {
    name: "sandbox_build",
    version: SANDBOX_BUILD_RUN_VERSION,
    async run(input: ToolRunInput): Promise<ArtifactFile[]> {
      const params = input.params;
      if (!isSandboxBuildParams(params)) throw new AnalysisError("tool_failed");
      const snapshot = snapshotOf(input);
      const provider = options.provider;
      if (provider === null) {
        input.log("No evaluation provider is configured on this worker.");
        throw new AnalysisError("evaluation_failed");
      }
      input.log("Sandbox build started.");
      const stored = await input.inputs.getVersion(params.sandboxVersionId);
      if (stored === null) throw new AnalysisError("tool_failed");
      const { version, source } = stored;
      // A draft that changed after this run was queued is a different build.
      if (
        source.sliceRunId !== params.sliceRunId ||
        source.sourceSnapshotId !== snapshot.snapshotId ||
        source.manifestSha256 !== params.manifestSha256 ||
        source.contractSha256 !== params.contractSha256 ||
        source.transformConfigSha256 !== params.transformConfigSha256 ||
        source.approvedTaskSha256 !== params.approvedTaskSha256
      )
        throw new AnalysisError("tool_failed");
      // And the content is what those hashes say: the manifest records them
      // as what it was built from, so a row whose table, tests, fixtures or
      // task moved away from its hash must not be built under it.
      const transformSha256 = sha256(
        canonicalJson(
          transformConfigOf({
            aliasRules: source.aliasRules,
            dependencyChoices: source.dependencyChoices,
            acceptanceTests: source.acceptanceTests,
            fixtures: source.fixtures,
            starterSha256: source.starterSha256,
          }),
        ),
      );
      if (
        transformSha256 !== params.transformConfigSha256 ||
        sha256(canonicalJson(source.approvedTask)) !== params.approvedTaskSha256
      ) {
        input.log("The draft's content does not match the hashes it carries.");
        throw new AnalysisError("tool_failed");
      }
      const slice = await loadSliceRun(
        input.inputs,
        params.sliceRunId,
        snapshot.snapshotId,
      );
      if (
        slice.manifestSha256 !== params.manifestSha256 ||
        slice.contractSha256 !== params.contractSha256
      )
        throw new AnalysisError("slice_unavailable");
      const { manifest, contract } = slice;
      const stubTexts = [...slice.stubs];
      input.signal.throwIfAborted();
      // Source bytes at the pinned commit, verified against the slice.
      const included = await readIncludedSource(input.sourceDir, manifest);
      input.log(
        `Read ${included.length} source files and ${stubTexts.length} stubs.`,
      );
      const first = manifest.included[0]?.path;
      const compilerOptions =
        first === undefined
          ? undefined
          : nearestCompilerOptions(input.sourceDir, first);
      // Aliasing, with the inverse proof. The spec rides along unscoped.
      const spec: SpecDraft | null = source.approvedTask.spec?.draft ?? null;
      const fixtures = source.fixtures?.fixtures ?? [];
      const scenario = source.fixtures?.scenario ?? null;
      const symbols = symbolsOf(contract);
      const symbolLeaves = jsonLeaves(CONTRACT_PSEUDO_PATH, symbols);
      const specLeaves =
        spec === null ? [] : jsonLeaves(SPEC_PSEUDO_PATH, spec);
      const fixtureLeaves = jsonLeaves(FIXTURES_PSEUDO_PATH, fixtures);
      const aliased = applyAliases(
        [
          ...included,
          ...stubTexts.map((stub) => ({ path: stub.module, text: stub.text })),
          ...symbolLeaves,
          ...specLeaves,
          ...fixtureLeaves,
          ...(scenario === null ? [] : [{ path: RUN_PATH, text: scenario }]),
        ],
        source.aliasRules,
      );
      const blockers: ProjectBlocker[] = [];
      let files: GeneratedFile[] = [];
      let importRewrites: SandboxBuildManifest["importRewrites"] = [];
      let renames: SandboxBuildManifest["renames"] = [];
      if (!aliased.ok) {
        for (const problem of aliased.problems)
          blockers.push({
            code: "alias_failed",
            file: problem.file,
            detail: `${problem.code}${problem.rule === null ? "" : ` (rule ${problem.rule})`}: ${problem.detail}`,
          });
        input.log(
          `Alias application refused with ${aliased.problems.length} problem(s).`,
        );
      } else {
        const sources: ProjectSource[] = included.map((file, index) => ({
          originalPath: file.path,
          path: aliased.files[index]?.path ?? file.path,
          text: aliased.files[index]?.text ?? file.text,
        }));
        const stubs: ProjectStub[] = stubTexts.map((stub, index) => {
          const file = aliased.files[included.length + index];
          return {
            module: stub.module,
            path: file?.path ?? stub.module,
            text: file?.text ?? stub.text,
          };
        });
        // The leaves back, in the order they went in.
        let at = included.length + stubTexts.length;
        const textsOf = (count: number) => {
          const texts = aliased.files
            .slice(at, at + count)
            .map((file) => file.text);
          at += count;
          return texts;
        };
        const aliasedContract = withSymbols(
          contract,
          withJsonLeaves(symbols, textsOf(symbolLeaves.length)),
        );
        const aliasedSpec =
          spec === null
            ? null
            : withJsonLeaves(spec, textsOf(specLeaves.length));
        const aliasedFixtures = withJsonLeaves(
          fixtures,
          textsOf(fixtureLeaves.length),
        );
        const aliasedScenario =
          scenario === null ? null : (aliased.files[at]?.text ?? scenario);
        /*
          A rule can still rename a value the shape depends on, such as a
          symbol's kind or a scenario's. What was valid before renaming must
          be valid after, or nothing is generated: a project built from a
          broken contract would carry the private names it failed to hide.
        */
        const broken = [
          stillReads(boundaryContractSchema, contract, aliasedContract)
            ? null
            : "contract",
          stillReads(specDraftSchema, spec, aliasedSpec) ? null : "spec",
          stillReads(fixtureListSchema, fixtures, aliasedFixtures)
            ? null
            : "fixtures",
        ].filter((name) => name !== null);
        for (const name of broken)
          blockers.push({
            code: "alias_failed",
            file: null,
            detail: `The alias table renamed a value the ${name} needs, so it no longer reads as one.`,
          });
        renames = aliased.renames;
        for (const blocker of source.scope.blockers)
          blockers.push({
            code: "scope_blocked",
            file: null,
            detail: `${blocker.code}: ${blocker.detail}`,
          });
        if (broken.length > 0) {
          input.log("Alias application broke the contract, spec or fixtures.");
        } else {
          const project = generateProject({
            version: {
              sandboxId: version.sandboxId,
              versionId: version.id,
              version: version.version,
              title: version.title,
              specSummary: version.specSummary,
              complexity: version.complexity,
              tags: version.tags,
            },
            manifest,
            contract: aliasedContract,
            sources,
            stubs,
            spec: aliasedSpec,
            dependencies: source.scope.dependencies,
            acceptanceTests: source.acceptanceTests,
            fixtures: aliasedFixtures,
            scenario: aliasedScenario,
            knownSpecifiers: NODE_BUILTINS,
            ...(compilerOptions === undefined ? {} : { compilerOptions }),
          });
          files = [...project.files];
          importRewrites = project.importRewrites;
          blockers.push(...project.blockers);
          input.log(
            `Generated ${project.files.length} files with ${project.importRewrites.length} import rewrites and ${project.blockers.length} blocker(s).`,
          );
        }
      }
      let baseline: BaselineReport | null = null;
      let evaluator: EvaluationEnvironment | null = null;
      if (blockers.length === 0) {
        const result = await baselineOf(provider, {
          label: version.id,
          files,
          acceptanceTests: source.acceptanceTests,
          blockers,
          signal: input.signal,
          log: input.log,
          now,
        });
        baseline = result.baseline;
        evaluator = result.evaluator;
      }
      const { manifest: buildManifest, written } = await writeBuildOutputs({
        outDir: input.outDir,
        toolVersion: SANDBOX_BUILD_RUN_VERSION,
        sandboxVersionId: version.id,
        aliasRules: source.aliasRules,
        bindings: {
          sourceSnapshotId: source.sourceSnapshotId,
          sourceCommitSha: snapshot.commitSha,
          sliceRunId: source.sliceRunId,
          manifestSha256: source.manifestSha256,
          contractSha256: source.contractSha256,
          transformConfigSha256: source.transformConfigSha256,
          approvedTaskSha256: source.approvedTaskSha256,
        },
        files,
        importRewrites,
        renames,
        dependencies: source.scope.dependencies,
        baseline,
        evaluator,
        blockers,
      });
      input.log(
        buildManifest.ready
          ? "Sandbox build ready for the publication gates."
          : `Sandbox build completed as diagnostic output (${blockers.length} blocker(s)).`,
      );
      return written;
    },
    /** A ready build's harness and toolchain become the draft's freeze evidence. */
    async committed({ runId, files, inputs }) {
      const file = files.find((item) => item.path === "build-manifest.json");
      if (file === undefined) return;
      const manifest = JSON.parse(
        await readFile(file.absolutePath, "utf8"),
      ) as SandboxBuildManifest;
      if (!manifest.ready) return;
      await inputs.recordBuildOutput(manifest.sandboxVersionId, runId, {
        harnessSha256: manifest.harnessSha256,
        toolchainDigest: manifest.toolchainDigest,
      });
    },
  };
}
